# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e80e8e0dc29cda99286cfda95cbe1c07ecd8faa7d68fb2577691a2be0b166b66f03e21bae64c573e41a5f945231eac88d51971880ee57627951a653a650071d

test:
  secret_key_base: 1d22a9e2c03118de2f1a78371aa0808b1459a5e8201a2c6990fe4d11dc56ff953d7106ec76dc0984f3a99b591c35830c3a859da8113b8fdca69baa5d1565d590

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
